# This is edit_repos.Rmd

Note: This is a companion file to `edit_webapps.rmd` in the ohi-webapps@master branch. 


```{r i think this chunk can be deleted now}

# ## run setup from create_all
# 
# ## set key
# key <- 'ohi-northeast'
# 
# # set vars by subcountry key
# source('create_init.R')   
# knitr::opts_knit$set(root.dir = dir_repos)
# source(sprintf('%s/ohi-webapps/create_init_sc.R', dir_github))    
# 
# ## clone repo and remotes
# ohirepos::clone_repo(dir_repos, dir_repo, git_url)
# 
# ## unpopulate layers, conf, etc. Doesn't push. 
# ohirepos::unpopulate_layers_conf(key, dir_repos, dir_repo, git_url, default_scenario)
# 
# ## set wd to scenario folder
# dir_scenario = file.path(dir_repo, basename(default_branch_scenario))
# if (!exists(dir_scenario)) dir.create(dir_scenario)
# knitr::opts_knit$set(root.dir = dir_scenario)
# 
# ## populate layers folder and layers.csv, and conf. Doesn't push. 
# ohirepos::populate_layers(key, dir_repo, lyrs_gl, dir_global, default_scenario, multi_nation=FALSE)
# populate_conf()
# populate_etc()
# 
# ## push draft branch
# source('~/github/ohi-webapps/ohi-functions.R')          
# setwd(dir_repo)
# push_branch('draft') # source('ohi-functions.r')
# system('git pull')

```


# Create prep repo

## 0. add info to `sc_studies_custom.csv` 

Add by hand to `ohi-webapps/custom/sc_studies_custom.csv`

## 1. set key

```{r key}
key <- 'can-atl'
```


## 2. Set directories etc

```{r setup}
dir_webapps <- '~/github/ohi-webapps'

source(file.path(dir_webapps, 'create_init.R'))
source(file.path(dir_webapps, 'create_init_sc.R'))
```

## 3. Create prep repo

```{r, knitr::opts_knit$set(root.dir = dir_repo)}
## create github repo on github.com
create_gh_repo(key, gh_token, github_user)

## create working dir
dir.create(dir_repo)

## add readme, .rproj, prep folder; commit and push
ohirepos::populate_init(key, dir_repo)
ohirepos::populate_prep(key)
```


## 4. Inspect Custom Shapefiles

For now, in prep_rdv.rmd, etc. 


## 5. Populate all the things

```{r}

## create scenario folder TODO: if doesn't exist
dir.create(dir_scenario, showWarning=FALSE)

## populate layers folder and layers.csv, and conf. Doesn't push. 
ohirepos::populate_layers(key, dir_repo, lyrs_gl, dir_global, dir_scenario, multi_nation = FALSE)
ohirepos::populate_conf(key, dir_scenario, dir_global) ## look at TODOs in functions.r, eg had to remove ICO gapfilling for NE
ohirepos::populate_etc(key, dir_scenario)

## ensure calculate_scores.r runs; save scores.csv 
calculate_scores_check(dir_scenario)

#TODO - [ ] look into pressures, resilience matrix stuff  <<-- do this next

## TODO: 
# functions.r
# search: 'temp/referencePoints.csv'
# replace: file.path(wd, 'temp/referencePoints.csv')


# create_repo_map
source('~/github/ohirepos/R/create_repo_map.R') ## build package and delete
ohirepos::create_repo_map(key, dir_spatial, dir_scenario) 

```

## Push!

```{r}
## push master branch   # TODO: move ohi-functions.R fxns to R folder as separate .r functions
setwd(dir_repo)
ohirepos::push_branch('master', sprintf('populate full %s repo', key))
system('git pull')

```




