# this is prep_cnc.Rmd
create new caledonia repo. 

## 1. setup

```{r setup, eval=F}
setwd('~/github/ohi-webapps')

source('create_init.R')            # load all libraries, set directories relevant to all keys
source('create_functions.R')       # all functions for creating and updating repos and webapps

key <- 'cnc'

dir_spatial = file.path(dir_M, 'git-annex/clip-n-ship', key, 'spatial') 
dir_layers  = file.path(dir_M, 'git-annex/clip-n-ship', key, 'layers') 
dir_custom  = file.path(dir_spatial, 'custom') 
dir_in      = file.path(dir_custom, 'ShapeFile_Region_CoralSeaMarinePark_EEZ_Limits') 

```

## Read shapefile, update name, resave

```{r explore shapefiles, eval=F}

## inspect
shp = readOGR(dsn = dir_in, layer = 'zee_officielle')
shp@data
  
plot(shp)

shp@data <- shp@data %>%
  dplyr::mutate(rgn_name = 'Nouvelle-Calédonie') %>%
  dplyr::select(rgn_id = ZEE_ID, 
                rgn_name, 
                area_km2 = AREA)

writeOGR(shp, dsn = dir_custom, layer = 'cnc_eez', driver = 'ESRI Shapefile', overwrite=TRUE) 

```

## Create required .csv files

have not done this 06/29/16; redo ohi-webapps@dev instead; otherwise borrow from Arctic...
