# This is prep_ohibc.Rmd

This script creates the British Columbia webapp. 

Each R chunk below will not be evaluated (ie, `{r, eval=F}`). 

## 1. setup
```{r setup, eval=F}

# libraries
library(dplyr)
library(tidyr)
library(readr)
library(stringr)
library(rgdal)
# library(raster)

# directories
# dir_neptune = c('Windows' = '//neptune.nceas.ucsb.edu/data_edit',
#                 'Darwin'  = '/Volumes/data_edit',
#                 'Linux'   = '/var/data/ohi')[[ Sys.info()[['sysname']] ]]
dir_custom_bc = '~/github/ohi-webapps/custom/ohibc'

# setwd
setwd('~/github/ohi-webapps')

```


## 2. copy BC map from @oharac's shape files  

Read in BC shapefile and begin formatting for OHI.


```{r copy bc map from shapefile, eval=F}

# read in shp files and save with desired headers in data frame. 
bc = readOGR(dsn = path.expand('~/github/ohibc/regions'),
              layer = 'ohibc_rgn')
# plot 
plot(bc)

# view data
bc@data

# clean orphan holes or invalid geometries 
source('~/github/ohi-webapps/custom/cleangeo_spatial_fxn.r')
bc_clean = cleangeo_spatial(bc)

# transforming from one CRS (Mercator which is in meters) to another (lat/long)
bc_proj = spTransform(bc, CRS('+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0')) # WGS84
bc_proj_clean <- cleangeo_spatial(bc_proj)

# save as shapefiles. will create 4 files: .dbf, .prj, .shp, .shx
writeOGR(bc_clean, dsn = file.path(dir_annex, 'ohibc/spatial/custom'), 
         layer = 'ohibc_shp', driver = 'ESRI Shapefile', overwrite=T) 

# create lookup table with unique rgn_ids
ohibc_rgns = bc_clean@data %>%
  select(rgn_name, rgn_id) %>%
  arrange(rgn_id)

write_csv(ohibc_rgns, 'custom/ohibc/ohibc_rgns_lookup.csv')

```

Temporary work-around for cleaned files

```{r tmp guy maps}

x = readOGR(dsn = file.path(dir_annex, 'ohibc/spatial'),
              layer = 'rgn_offshore_gcs')

writeOGR(x, dsn = file.path(dir_annex, 'ohibc/spatial/custom'), 
         layer = 'ohibc_shp_tmp_guy', driver = 'ESRI Shapefile', overwrite=T) 

# `ohibc_shp_tmp_guy` will be listed first which will work with algorithm of custom_maps()


```
